### ISSUE TITLE
Grunt run error

### ISSUE THREAD

**Issue by mig-25** [micahgodbolt/sassbitesdemo#8]
I have just converted to Mac OS Yosemite, and this is my first experience with Mac environment. 
I have been able to run this repo on a Wndows 8.1 machine, had to do my share of custom settings for Hologram and Redcarpet to make it to work.
But I thought this would run without any issues on a Mac. I have cloned the repo, and followed the instructions, but I get the following error:

``` javascript
Sohails-MacBook-Pro:sass-summit-2014 sohail$ grunt
Running "shell:bundler" (shell) task
Using sass 3.4.5
Using sassy-maps 0.4.0
Using breakpoint 2.5.0
Using chunky_png 1.3.1
Using multi_json 1.10.1
Using compass-core 1.0.1
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.4
Using ffi 1.9.6
Using rb-inotify 0.9.5
Using compass 1.0.1
Using redcarpet 3.2.0
Using rouge 1.7.2
Using hologram 1.2.0
Using sass-globbing 1.1.1
Using susy 2.1.3
Using bundler 1.7.12
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

Running "shell:bower" (shell) task
bower eq.js#~1.4.1              cached git://github.com/Snugug/eq.js.git#1.4.1
bower eq.js#~1.4.1            validate 1.4.1 against git://github.com/Snugug/eq.js.git#~1.4.1
bower Cortana#~1.2.7            cached git://github.com/Yago31/Cortana.git#1.2.8
bower Cortana#~1.2.7          validate 1.2.8 against git://github.com/Yago31/Cortana.git#~1.2.7
bower domready#*                cached git://github.com/ded/domready.git#1.0.7
bower domready#*              validate 1.0.7 against git://github.com/ded/domready.git#*
bower                           EACCES EACCES, mkdir '/Users/sohail/GitHub/sass-summit-2014/bower_components'

Stack trace:
Error: EACCES, mkdir '/Users/sohail/GitHub/sass-summit-2014/bower_components'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.35
OS: Darwin 14.0.0 x64
Warning: Command failed: bower                           EACCES EACCES, mkdir '/Users/sohail/GitHub/sass-summit-2014/bower_components'

Stack trace:
Error: EACCES, mkdir '/Users/sohail/GitHub/sass-summit-2014/bower_components'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.35
OS: Darwin 14.0.0 x64
 Use --force to continue.

Aborted due to warnings.
```

I hope this is due to my poor knowledge of the mac environment. I have beeb successful in compiling a previous version of the sassbitesdemo on the mac with npm, bower, bundler and sass.

thanks
-Sohail

**Comment by micahgodbolt** [comment]
it's possibly a file privilege issue

check out https://github.com/npm/npm/issues/5869#issuecomment-51003238
